server:
  port: 9090
#To include all the endpoints of actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

#mysqldependencies
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/springbootdb?createDatabaseIfNotExist=true
#    username: root
#   password: W;?G16<5&t;s

#Mongodb config
spring:
  data:
    mongodb:
      host: localhost
      port:  27017
      database: restdb

